name: Main-Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
         # Linux only, for now
          - os: windows-latest
            artifact_name: syclinfo-ubuntu-windows
          - os: ubuntu-24.04
            artifact_name: syclinfo-ubuntu-24.04

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # ~~  DEPENDENCY INSTALLATION ~~
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
      - name: Install SYCL dependencies(Intel oneAPI) Linux
        if: matrix.os == 'ubuntu-24.04' 
        run: |
          # Install Intel oneAPI DPC++ Compiler and dependencies
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update
          sudo apt-get install -y \
            intel-oneapi-dpcpp-cpp-2025.2 \
            intel-oneapi-dpcpp-ct \
            intel-oneapi-mkl-devel \
            opencl-headers \
            ocl-icd-opencl-dev

      - name: Install SYCL dependencies(Intel oneAPI) Windows
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://registrationcenter-download.intel.com/akdlm/IRC_NAS/9a9a39c7-f6f4-4196-8ff8-bfc735fd68e7/w_BaseKit_p_2025.2.0.75_web.exe" -OutFile "oneapi_web.exe"
          Start-Process -FilePath ".\oneapi_web.exe" -ArgumentList "--silent", "--eula", "accept", "--components", "intel.oneapi.win.dpcpp-compiler" -Wait

      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      # ~~~         BUILD          ~~~
      # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      - name: Build
        run: |
         source /opt/intel/oneapi/setvars.sh
         export CXX=/opt/intel/oneapi/compiler/latest/bin/icpx
         $CXX --version
         icx -fsycl syclinfo.cpp -o syclinfo

      - name: Build on Windows
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat"
          icx -fsycl syclinfo.cpp -o syclinfo.exe

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: ${{ matrix.artifact_name }}
          path: syclinfo



            
